spring.application.name=QuizzAppli

# Laisse Render choisir le port (8080 par défaut), sinon 8086 en local
server.port=${PORT:8086}

# --- CONFIGURATION BASE DE DONNÉES ---
# On utilise les variables de Render si elles existent, sinon ton MySQL local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/quiz_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Lyne@002#Assouh}

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# AJOUT DE SÉCURITÉ : Aide Hibernate à choisir le bon dialecte automatiquement
# Sur Render, il détectera PostgreSQL. En local, il détectera MySQL.
spring.jpa.open-in-view=false